# Generated by Django 5.2.8 on 2025-11-15 05:47

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='call_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='connections',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='connectionsDescription',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='height',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_createdby',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscribtionDate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscribtionExpire',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscribtionStatus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='terms',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tiktokLink',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userDiWohtiKaTaruf',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='userKaTaruf',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='tempuser', error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
