# Generated by Django 5.2.8 on 2025-11-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_apiuser_product_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.DeleteModel(
            name='APIUser',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
