# Generated by Django 5.2.8 on 2025-11-26 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
