# Generated by Django 5.2.8 on 2025-11-26 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('purchase_date', models.IntegerField()),
                ('purchase_month', models.CharField(max_length=20)),
                ('purchase_year', models.IntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_username', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
