# Generated by Django 5.2.8 on 2025-11-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(unique=True)),
                ('purchase_date', models.IntegerField()),
                ('purchase_month', models.CharField(max_length=20)),
                ('purchase_year', models.IntegerField()),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('last_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
                ('user_username', models.CharField(max_length=150)),
                ('user_first_name', models.CharField(max_length=150)),
                ('user_last_name', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('product_is_available', models.BooleanField()),
                ('product_status', models.CharField(blank=True, max_length=50, null=True)),
                ('product_category', models.CharField(blank=True, max_length=50, null=True)),
                ('product_sku', models.CharField(blank=True, max_length=50, null=True)),
                ('product_stock', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
